Create event card
uclaacm/ai.uclaacm.com pull request #9
Opened 2022-09-17 22:19 UTC by JensonChoi

# Light theme
<img width="261" alt="light-event" src="https://user-images.githubusercontent.com/61100042/190878119-bb228308-967d-4cb5-ba2b-16003bebbdfc.png">

# Dark theme
<img width="265" alt="dark-event" src="https://user-images.githubusercontent.com/61100042/190878123-8e8ece0f-947b-4697-90cc-4464462018cb.png">

# Manual testing
Add the following code to one of the pages:
`<EventCard
        title='event card thing'
        datetime='date/time'
        location='place'
        blurb='smol blub'
      ></EventCard>`

2022-09-18 05:09 UTC, amanongithub7 approved these changes

2022-10-05 17:51 UTC, amanongithub7 requested changes

2022-10-05 17:51 UTC, amanongithub7 commented on src/components/event-card.jsx
> +        <Heading fontSize='15px'>Date: {datetime}</Heading>
can we have the graphic of the event displayed on the card? and also a field for a link to the event would also be great!

2022-10-05 19:57 UTC, JensonChoi commented on src/components/event-card.jsx
> +        <Heading fontSize='15px'>Date: {datetime}</Heading>
there are 2 options that i can do:
1. increase the size of the event card to fit in the graphic and the link
2. make the event card flippable, in which case, the graphic and the link would go on the back side

2023-05-05 04:54 UTC, closed without merging